name: ContaoTwo
main: de.minestar.contao2.core.Core
version: ${pom.version}
depend: [GroupManager, MinestarCore]
commands:
  user:
    description: Contao related commands
    usage: /user
  ppay:
    description: PayPlugin related commands
    usage: /ppay 
  who:
    description: List players
    usage: /who
    aliases: ['list', 'online']
  stats:
    description: Bla bla
    usage: /stats